### ISSUE TITLE
It seems that the alpha and beta in config file will not be passed into the "get_sde_loss_fn".

### ISSUE THREAD

**Issue by BIGKnight** [sony/fp-diffusion#2]
Hi, 
I just noticed that alpha and beta in config file will not be passed into the "get_sde_loss_fn", which means that the default code will only run in the mode of vanilla score-based models. 

https://github.com/sony/fp-diffusion/blob/dea704eb5ae11ad26342f3610dc667cfc9813534/losses.py#L199

**Comment by ChiehHsinJesseLai** [comment]
Hi, 

Thanks for checking.
The loss https://github.com/sony/fp-diffusion/blob/68d61e04b1bc518f335a1bfc2700922b14aad5e0/losses.py#L199 is corrected.
